# -*- mode: cmake; eval: (hl-line-mode 0);-*-
function(build_and_install sources_l type linklibs_l properties_l install)
  string(REPLACE "${CMAKE_SOURCE_DIR}/" "" progname_tmp ${CMAKE_CURRENT_SOURCE_DIR})
  string(REPLACE "/" "_" progname ${progname_tmp})
  string(REPLACE " " ";" sources ${sources_l})

  if(${type} STREQUAL "PROGRAM")
    message("adding program \"${progname}\"")
    add_executable(${progname} ${sources})
  elseif(${type} STREQUAL "SHARED")
    message("adding library \"${progname}\"")
    add_library(${progname} SHARED ${sources})
  else()
    message("Target \"${progname}\" won't build anything")
    return()
  endif()

  foreach(loopvar IN LISTS properties)
    set_property(TARGET ${progname} PROPERTY ${loopvar})
  endforeach(loopvar)
  foreach(loopvar IN LISTS linklibs)
    string(REPLACE "_" "/" linklibs_d ${loopvar})
    unset(libloc CACHE)
    if(${loopvar} STREQUAL " ")
      return()
    endif()
    find_library(libloc ${loopvar} PATHS "${CMAKE_BINARY_DIR}/${linklibs_d}")
    message("${progname} links to ${loopvar}, searching in ${CMAKE_BINARY_DIR}/${linklibs_d}, found in ${libloc}")
    target_link_libraries(${progname} ${libloc})
  endforeach(loopvar)

  message("${INCLUDE_DIRECTORIES}")
  message("${SYSTEM_INCLUDE_DIRECTORIES}")
  message("${CMAKE_INCLUDE_DIRECTORIES}")
  

  if(${install} MATCHES "NO.*")
    message("Target \"${progname}\" won't install anything")
  else()
    if(${type} STREQUAL "PROGRAM")
      install(TARGETS ${progname} RUNTIME DESTINATION "/usr/local/bin/")
    elseif(${type} STREQUAL "SHARED")
      install(TARGETS ${progname} LIBRARY DESTINATION "/usr/local/lib/")
    endif()
  endif()
endfunction(build_and_install)
